version: '3.5'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    working_dir: /var/www/api
    volumes:
      - ./backend:/var/www/api
      - ${PURCHASED_FILES_DIRECTORY}
    env_file:
      - .env
    depends_on:
      - elasticsearch
    ports:
      - ${DATA_MART_API_PORT}:${DATA_MART_API_PORT}
    network_mode: host
  frontend:
    build:
      context: ./front-end
      dockerfile: ./Dockerfile
    volumes:
      - ./front-end:/front-end
    env_file:
      - .env
    depends_on:
      - backend
    network_mode: host
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    expose:
      - 9200
      - 9300
    volumes:
      - esdata:/usr/share/elasticsearch/data
    tty: true
    network_mode: host
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    restart: always
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
#                volumes:
#                        - ${KIBANA_CONF_YML_FILE}:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    tty: true
    network_mode: host
  # encryptor:
  #   build:
  #     context: .
  #     dockerfile: encryptor.docker
  #   ports:
  #     - 3030:3030
  #   volumes:
  #     - ./encryptor:/var/www/encryptor
volumes:
  esdata:
