version: '3.5'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - ${DATA_VALIDATOR_API_PORT}:${DATA_VALIDATOR_API_PORT}
    env_file:
      - .env
    depends_on:
      - elasticsearch
    network_mode: host
  frontend:
    build:
      context: ./front-end
      dockerfile: ./Dockerfile
    volumes:
      - ./front-end:/usr/src/app
    ports:
      - ${REACT_APP_PRODUCTION_PORT}:${REACT_APP_PRODUCTION_PORT}
    env_file:
      - .env
    depends_on:
      - backend
    network_mode: host
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    expose:
      - 9200
      - 9300
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 1s
      timeout: 10s
      retries: 30
    network_mode: host
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    restart: always
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
#                volumes:
#                        - ${KIBANA_CONF_YML_FILE}:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    tty: true
    network_mode: host
  # encryptor:
  #   build:
  #     context: .
  #     dockerfile: encryptor.docker
  #   ports:
  #     - 3030:3030
  #   volumes:
  #     - ./encryptor:/var/www/encryptor
volumes:
  esdata:
