version: '3.5'
services:
  backend:
    build:
      context: .
      dockerfile: backend.docker
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3005:3005
    depends_on:
      - elasticsearch
  frontend:
    build:
      context: .
      dockerfile: frontend.docker
    volumes:
      - ./front-end:/usr/src/app
    ports:
      - 3008:3008
    depends_on:
      - backend
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
      - discovery.type=${ELASTIC_DISCOVERY_TYPE}
      - xpack.security.enabled=${ELASTIC_XPACK_SECURITY}
    expose:
      - 9200
      - 9300
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    tty: true
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    restart: always
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
#                volumes:
#                        - ${KIBANA_CONF_YML_FILE}:/usr/share/kibana/config/kibana.yml
    ports:
      - ${KIBANA_OUTSIDE_PORT}:5601
    depends_on:
      - elasticsearch
    tty: true
  # encryptor:
  #   build:
  #     context: .
  #     dockerfile: encryptor.docker
  #   ports:
  #     - 3030:3030
  #   volumes:
  #     - ./encryptor:/var/www/encryptor
volumes:
  esdata: